### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [danielpselph/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The four methods I chose for **Class #1** represent behaviors or actions.
```
A better name for `new_customer` would be `add_new_customer` or `add_customer` because we want the naming to clearly represent an action by being a verb or action phrase.
```
- [x] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The four methods I chose for **Class #2** represent behaviors or actions.
- [x] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 
```
We'd like for you to model a class that you might find in a restaurant for the second example. We don't want you to model the same class twice, although I appreciate that you changed up the methods and attributes! Go ahead and model another class that exists within a restaurant. Something like Employee, Customer, Kitchen, Menu, Bar, Kitchen, etc. 
```
Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 
```
This is a solid assessment Daniel! The only thing is as I stated above we would like to see a different class modeled for class 2/object 2. Go ahead and create a new class file and a new object file and choose a class to model. Make sure all of your methods are clearly verbs/action-phrases. You can commit and push these files together once you've added them. I'm looking forward to seeing the updates! Thanks Daniel
```
### Assessment Results
- [x] Technical Ready
- [ ] Pending
- [ ] Not Technical Ready

Class #3 checklist
- [x] The four attributes I chose for **Class #3** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 3**.
- [x] The four methods I chose for **Class #3** represent behaviors or actions.
- [x] I described what the methods do in **Class 3**, including which attributes they use or modify.
- [x] Class 3 is something one would find in a restaurant

Class #3 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object.
